kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: ecointet
    password: 7d5219ab-ee5b-4111-b5f5-21a5623d3a48
    repo: ecointet/harness-webapp-demo
    tags: v3