apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecointet-webapp
  namespace: production
spec:
  selector:
    matchLabels:
      app: ecointet-webapp
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: ecointet-webapp
    spec:
      containers:
      - name: ecointet-webapp
        image: ecointet/harness-webapp-demo:stable
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: production/ecointet-pvc
          mountPath: "/data-ext"