apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ecointet-webapp
  namespace: production
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "harness-platform-demo-ip"
spec:
  backend:
    serviceName: nodeport-ecointet-webapp
    servicePort: 8000
    