apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-harness-demo-app
  namespace: production
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: ecointet-webapp
  type: NodePort