apiVersion: v1
kind: Service
metadata:
  name: nodeport-harness-platform-demo
  namespace: production
spec:
  ports:
  - port: 8000
    protocol: TCP
  selector:
    app: ecointet-webapp
  type: NodePort